### ISSUE TITLE
[Question] How to build/run project .

### ISSUE THREAD

**Issue by fanta759** [mengxiong10/vue-datepicker-next#44]
**Vue-datepicker-next version**: 1.0.3
**Vue version**: 3

I want to test settings to run vue-datepicker-next with @vue/compat. But I can't make it build or run.
I have the same error : `esbuild: Failed to install correctly`

I run on windows 11 in WSL with node 18.16 and npm 9.5.1.
I run npm i then npm start and i got :
```
$ npm run start

> vue-datepicker-next@1.0.3 start
> npm run dev


> vue-datepicker-next@1.0.3 dev
> vite --host 0.0.0.0

/home/afantou/dev/Perso/vue-datepicker-next/node_modules/esbuild/bin/esbuild:2
throw new Error(`esbuild: Failed to install correctly
^

Error: esbuild: Failed to install correctly

Make sure you don't have "ignore-scripts" set to true. You can check this with
"npm config get ignore-scripts". If that returns true you can reset it back to
false using "npm config set ignore-scripts false" and then reinstall esbuild.

If you're using npm v7, make sure your package-lock.json file contains either
"lockfileVersion": 1 or the code "hasInstallScript": true. If it doesn't have
either of those, then it is likely the case that a known bug in npm v7 has
corrupted your package-lock.json file. Regenerating your package-lock.json file
should fix this issue.

    at Object.<anonymous> (/home/afantou/dev/Perso/vue-datepicker-next/node_modules/esbuild/bin/esbuild:2:7)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.16.0
failed to load config from /home/afantou/dev/Perso/vue-datepicker-next/vite.config.ts
error when starting dev server:
Error: The service was stopped
    at /home/afantou/dev/Perso/vue-datepicker-next/node_modules/esbuild/lib/main.js:1217:25
    at /home/afantou/dev/Perso/vue-datepicker-next/node_modules/esbuild/lib/main.js:609:9
    at Socket.afterClose (/home/afantou/dev/Perso/vue-datepicker-next/node_modules/esbuild/lib/main.js:587:7)
    at Socket.emit (node:events:525:35)
    at Socket.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

What wrong i do ?
Thanks

**Comment by fanta759** [comment]
I found the solution here : https://lzfblog.cn/?p=256

Juste to run : `node node_modules/esbuild/install.js`
All good
